name: fr_storage
description: Box-based Flutter key-value storage using ObjectBox on native platforms and IndexedDB on Web.
version: 0.1.0
repository: https://github.com/Hu-Wentao/flowr
topics:
  - storage
  - encryption
  - objectbox
  - indexeddb

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0
  flat_buffers: ^25.9.23
  flutter_secure_storage: ^9.2.0
  idb_shim: ^2.6.2
  objectbox: ^5.3.2
  objectbox_flutter_libs: ^5.3.2
  pointycastle: ^4.0.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^5.3.2
