#!/usr/bin/env python3
"""Generate or check a component HTTP service from its BFF Markdown artifact."""

from __future__ import annotations

import argparse
import json
import os
import re
import stat
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

from contract_core import (
    ContractError,
    bracket_refs,
    find_package_pubspec,
    has_direct_dependency,
    require_file,
)
from contract_parser import ComponentContract, parse_component, parse_page
from resolve import find_repo_root, load_config, require_mapping, require_string


GENERATED_SERVICE_MARKER = "// GENERATED BY fr-mvvm-contract: generate_service.py"
SERVICE_PATTERN = re.compile(r"^\[([A-Za-z_][A-Za-z0-9_]*)\]$")
ENDPOINT_PATTERN = re.compile(
    r"^###\s+(GET|POST|PUT|PATCH|DELETE)\s+(\S+)\s*$", re.MULTILINE
)


@dataclass(frozen=True)
class RequestField:
    """One top-level request field emitted in the BFF JSON5 example."""

    name: str
    dart_type: str


@dataclass(frozen=True)
class BffEndpoint:
    """One supported BFF endpoint parsed from generated Markdown."""

    method: str
    path: str
    request_type: str
    response_type: str
    request_fields: tuple[RequestField, ...] = ()


@dataclass(frozen=True)
class ServiceConfig:
    """Project-owned defaults for generated component services."""

    base_url: str | None


def parse_bff_markdown(content: str) -> tuple[BffEndpoint, ...]:
    """Parse every endpoint shape emitted by fr_acdd."""

    matches = list(ENDPOINT_PATTERN.finditer(content))
    if not matches:
        raise ContractError("service generation requires at least one BFF endpoint")
    endpoints: list[BffEndpoint] = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(content)
        block = content[match.end() : end]
        request = re.search(r"^- Request DTOs:\s*(.+)$", block, re.MULTILINE)
        response = re.search(r"^- Response DTOs:\s*(.+)$", block, re.MULTILINE)
        request_refs = bracket_refs([request.group(1)]) if request else []
        response_refs = bracket_refs([response.group(1)]) if response else []
        if len(request_refs) != 1 or len(response_refs) != 1:
            raise ContractError(
                "each BFF endpoint requires exactly one request DTO and one response DTO"
            )
        request_block = re.search(
            r"#### Request JSON5\s*```json5\s*([\s\S]*?)```", block
        )
        fields: list[RequestField] = []
        if request_block:
            lines = request_block.group(1).splitlines()
            for line_index, line in enumerate(lines[:-1]):
                type_match = re.match(r"^  // Dart type:\s*(.+?)\s*$", line)
                if not type_match:
                    continue
                field_match = re.match(
                    r"^  ([A-Za-z_][A-Za-z0-9_]*):", lines[line_index + 1]
                )
                if field_match:
                    fields.append(
                        RequestField(field_match.group(1), type_match.group(1))
                    )
        endpoints.append(
            BffEndpoint(
                method=match.group(1),
                path=match.group(2),
                request_type=request_refs[0],
                response_type=response_refs[0],
                request_fields=tuple(fields),
            )
        )
    return tuple(endpoints)


def contract_endpoints(component: ComponentContract) -> tuple[BffEndpoint, ...]:
    """Read ordered endpoint identities directly from the approved contract."""

    endpoints: list[BffEndpoint] = []
    current: re.Match[str] | None = None
    refs: list[str] = []

    def append_current() -> None:
        if current is None:
            return
        if len(refs) != 2:
            raise ContractError("each BFF endpoint requires one approved Req/Rsp pair")
        endpoints.append(
            BffEndpoint(current.group(1), current.group(2), refs[0], refs[1])
        )

    for line in component.sections.get("BFF-API", []):
        match = re.match(r"^-?\s*(GET|POST|PUT|PATCH|DELETE)\s+(\S+)\s*$", line.strip())
        if match:
            append_current()
            current = match
            refs = []
            continue
        if current is not None:
            refs.extend(bracket_refs([line]))
    append_current()
    if not endpoints:
        raise ContractError(
            "component service requires at least one approved BFF endpoint"
        )
    return tuple(endpoints)


def load_service_config(component_file: Path) -> ServiceConfig:
    """Load optional project defaults without requiring configuration."""

    repo_root = find_repo_root(component_file.parent)
    config_path = repo_root / ".agents/skills-config/fr-mvvm-contract/config.yaml"
    config, _ = load_config(config_path)
    if not config:
        return ServiceConfig(base_url=None)
    if config.get("schema") != "fr-mvvm-contract.config.v1":
        raise ContractError("config.yaml schema must be fr-mvvm-contract.config.v1")
    service = require_mapping(config.get("service", {}), "service")
    raw_base_url = service.get("base_url")
    if raw_base_url is None:
        return ServiceConfig(base_url=None)
    base_url = require_string(raw_base_url, "service.base_url")
    parsed = urlparse(base_url)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ContractError("service.base_url must be an absolute HTTP(S) URL")
    return ServiceConfig(base_url=base_url.rstrip("/") + "/")


def add_directive(source: str, directive: str, *, kind: str) -> str:
    """Add one Dart import or part directive without reordering existing ones."""

    if directive in source:
        return source
    matches = list(
        re.finditer(
            rf"^\s*{kind}\s+['\"][^'\"]+['\"](?:\s+as\s+\w+)?\s*;\s*$",
            source,
            re.MULTILINE,
        )
    )
    if matches:
        index = matches[-1].end()
        return source[:index] + "\n" + directive + source[index:]
    return directive + "\n" + source


def dart_string(value: str) -> str:
    """Return a deterministic Dart string literal."""

    return json.dumps(value, ensure_ascii=False)


def operation_name(service_type: str, request_type: str) -> str:
    """Derive one stable lowerCamelCase service operation from its request DTO."""

    request_stem = request_type
    for suffix in ("BffReq", "Req"):
        if request_stem.endswith(suffix):
            request_stem = request_stem.removesuffix(suffix)
            break
    else:
        raise ContractError(
            f"request DTO {request_type} must end in BffReq to name a service operation"
        )
    service_stem = service_type.removesuffix("Service")
    if request_stem.startswith(service_stem) and request_stem != service_stem:
        request_stem = request_stem.removeprefix(service_stem)
    if not request_stem:
        request_stem = service_stem
    return request_stem[0].lower() + request_stem[1:]


def path_names(endpoint: BffEndpoint) -> tuple[str, ...]:
    return tuple(
        match.group(1)
        for match in re.finditer(
            r"(?::|\{)([A-Za-z_][A-Za-z0-9_]*)(?:\}|(?=/|$))",
            endpoint.path,
        )
    )


def render_endpoint(
    *, service_type: str, endpoint: BffEndpoint
) -> tuple[str, str | None]:
    """Render one Retrofit method and optional typed path-parameter adapter."""

    operation = operation_name(service_type, endpoint.request_type)
    names = path_names(endpoint)
    fields = {field.name: field for field in endpoint.request_fields}
    missing_path_fields = [name for name in names if name not in fields]
    if missing_path_fields:
        raise ContractError(
            "BFF path fields are missing top-level request JSON5 definitions: "
            + ", ".join(missing_path_fields)
        )
    retrofit_path = re.sub(r":([A-Za-z_][A-Za-z0-9_]*)", r"{\1}", endpoint.path)
    payload_name = "queries" if endpoint.method == "GET" else "body"
    payload_annotation = "@Queries()" if endpoint.method == "GET" else "@Body()"
    raw_operation = f"_{operation}Request"
    parameters = [
        f"@Path('{name}') required {fields[name].dart_type} {name}," for name in names
    ]
    parameters.append(
        f"{payload_annotation} required Map<String, dynamic> {payload_name},"
    )
    parameter_block = "\n".join(f"    {line}" for line in parameters)
    method = (
        f"  @{endpoint.method}({dart_string(retrofit_path)})\n"
        f"  Future<{endpoint.response_type}> {raw_operation}({{\n"
        f"{parameter_block}\n"
        "  });"
    )
    remove_lines = "\n".join(f"    data.remove({dart_string(name)});" for name in names)
    arguments = [f"{name}: request.{name}," for name in names]
    arguments.append(f"{payload_name}: data,")
    argument_block = "\n".join(f"      {line}" for line in arguments)
    remove_block = f"{remove_lines}\n" if remove_lines else ""
    adapter = (
        f"  Future<{endpoint.response_type}> {operation}("
        f"{endpoint.request_type} request) {{\n"
        "    final data = Map<String, dynamic>.from(request.toJson());\n"
        f"{remove_block}\n"
        f"    return {raw_operation}(\n"
        f"{argument_block}\n"
        "    );\n"
        "  }"
    )
    return method, adapter


def render_service_source(
    *,
    component_name: str,
    service_file_name: str,
    service_type: str,
    endpoints: tuple[BffEndpoint, ...],
    config: ServiceConfig,
) -> bytes:
    """Render one component Retrofit service with semantic operations."""

    generated_part = service_file_name.removesuffix(".dart") + ".g.dart"
    base_annotation = (
        f"@RestApi(baseUrl: {dart_string(config.base_url)})"
        if config.base_url
        else "@RestApi()"
    )
    operations = [
        operation_name(service_type, endpoint.request_type) for endpoint in endpoints
    ]
    duplicates = sorted({name for name in operations if operations.count(name) > 1})
    if duplicates:
        raise ContractError(
            "BFF request DTOs produce duplicate service operations: "
            + ", ".join(duplicates)
        )
    rendered = [
        render_endpoint(service_type=service_type, endpoint=e) for e in endpoints
    ]
    method_block = "\n\n".join(method for method, _ in rendered)
    adapters = [adapter for _, adapter in rendered if adapter is not None]
    extension = ""
    if adapters:
        extension = (
            f"\n\nextension {service_type}Operations on {service_type} {{\n"
            + "\n\n".join(adapters)
            + "\n}\n"
        )
    source = f"""{GENERATED_SERVICE_MARKER}
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import '{component_name}';

part '{generated_part}';

{base_annotation}
abstract class {service_type} {{
  factory {service_type}(Dio dio, {{String? baseUrl}}) = _{service_type};

{method_block}
}}{extension}
"""
    return source.encode("utf-8")


def plan_service(
    component: ComponentContract,
    bff_content: bytes,
    *,
    shell_content: bytes | None = None,
) -> tuple[dict[Path, bytes], Path | None]:
    """Plan shell/service writes from freshly generated BFF Markdown."""

    declaration = component.bff_service
    if declaration is None:
        if "BFF-API" in component.sections:
            raise ContractError(
                "BFF-JSON requires `BFF Service: [Type]`; contract-only delivery "
                "is not supported"
            )
        return {}, None
    service = SERVICE_PATTERN.fullmatch(declaration)
    if not service:
        raise ContractError(
            "BFF Service must directly reference one generated Dart class"
        )
    service_type = service.group(1)

    parsed = parse_bff_markdown(bff_content.decode("utf-8"))
    approved = contract_endpoints(component)
    parsed_identity = tuple(
        (e.method, e.path, e.request_type, e.response_type) for e in parsed
    )
    approved_identity = tuple(
        (e.method, e.path, e.request_type, e.response_type) for e in approved
    )
    if parsed_identity != approved_identity:
        raise ContractError(
            "BFF artifact endpoint or DTO types do not match the approved contract"
        )

    shell = Path(component.component_file)
    service_file = shell.with_name(f"{shell.stem}.srv.dart")
    shell_source = (
        shell_content.decode("utf-8")
        if shell_content is not None
        else require_file(shell, "component library")
    )
    import_directive = f"import '{service_file.name}';"
    existing = (
        service_file.read_text(encoding="utf-8") if service_file.exists() else None
    )
    if existing is not None:
        if not re.search(rf"\bclass\s+{re.escape(service_type)}\b", existing):
            raise ContractError(
                f"existing BFF service {service_file} does not declare {service_type}"
            )
        updated_shell = add_directive(shell_source, import_directive, kind="import")
        return (
            {shell: updated_shell.encode("utf-8")}
            if updated_shell != shell_source
            else {}
        ), service_file

    pubspec = find_package_pubspec(shell)
    missing_dependencies = [
        package
        for package, section in (
            ("dio", "dependencies"),
            ("efficient_dio_logger", "dependencies"),
            ("retrofit", "dependencies"),
            ("retrofit_generator", "dev_dependencies"),
            ("build_runner", "dev_dependencies"),
        )
        if not has_direct_dependency(pubspec, package, section=section)
    ]
    if missing_dependencies:
        raise ContractError(
            f"{pubspec} must directly declare BFF Service dependencies: "
            + ", ".join(missing_dependencies)
        )
    config = load_service_config(shell)
    updated_shell = add_directive(shell_source, import_directive, kind="import")
    updates: dict[Path, bytes] = {
        service_file: render_service_source(
            component_name=shell.name,
            service_file_name=service_file.name,
            service_type=service_type,
            endpoints=parsed,
            config=config,
        )
    }
    if updated_shell != shell_source:
        updates[shell] = updated_shell.encode("utf-8")
    return updates, service_file


def atomic_write(path: Path, content: bytes) -> None:
    """Replace one file without exposing a partial write."""

    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    os.close(descriptor)
    temporary = Path(temporary_name)
    try:
        temporary.write_bytes(content)
        temporary.chmod(mode)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def apply_updates(updates: dict[Path, bytes]) -> None:
    """Apply service updates and restore originals after a failed commit."""

    originals = {
        path: path.read_bytes() if path.is_file() else None for path in updates
    }
    try:
        for path, content in updates.items():
            atomic_write(path, content)
    except Exception as error:
        for path, original in reversed(list(originals.items())):
            if original is None:
                path.unlink(missing_ok=True)
            else:
                atomic_write(path, original)
        raise ContractError(
            f"service generation failed; files were restored: {error}"
        ) from error


def generate_service(component: ComponentContract, *, check: bool) -> Path | None:
    """Generate or verify the component service from its current BFF file."""

    bff_file = Path(component.component_file).with_suffix(".bff.md")
    if component.bff_service is None:
        if "BFF-API" in component.sections:
            raise ContractError(
                "BFF-JSON requires `BFF Service: [Type]`; contract-only delivery "
                "is not supported"
            )
        return None
    bff_content = bff_file.read_bytes() if bff_file.is_file() else None
    if bff_content is None:
        raise ContractError(f"BFF artifact does not exist: {bff_file}")
    updates, service_file = plan_service(component, bff_content)
    if check:
        for path, content in updates.items():
            if not path.is_file() or path.read_bytes() != content:
                raise ContractError(f"generated BFF service is stale: {path}")
        if service_file and service_file.is_file():
            generated = service_file.with_name(f"{service_file.stem}.g.dart")
            if not generated.is_file():
                raise ContractError(
                    f"generated Retrofit implementation does not exist: {generated}; "
                    "run build_runner"
                )
        return service_file
    apply_updates(updates)
    return service_file


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--page-file", type=Path)
    group.add_argument("--component-file", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        component = (
            parse_page(args.page_file.resolve()).component
            if args.page_file
            else parse_component(args.component_file.resolve())
        )
        service = generate_service(component, check=args.check)
    except (ContractError, OSError, UnicodeError) as error:
        print(f"contract error: {error}", file=sys.stderr)
        return 2
    if service is None:
        print("BFF service: not applicable for explicit API mode")
    else:
        action = "current" if args.check else "generated"
        print(f"BFF service {action}: {service}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
