#!/usr/bin/env python3
"""Generate Dart Retrofit declarations and JSON DTOs from OpenAPI JSON."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from fnmatch import fnmatchcase
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any
from urllib.parse import unquote

from resolve import (
    DartGenericWrapperRule,
    ResolveError,
    load_dart_generic_wrapper_rules,
)

MARKER = "// GENERATED BY fr-mvvm-contract/scripts/openapi_to_retrofit.py; DO NOT EDIT."
LEGACY_MARKER = "// GENERATED BY tools/openapi_to_retrofit.py; DO NOT EDIT."
BUILD_RUNNER_MARKER = "// GENERATED CODE - DO NOT MODIFY BY HAND"
HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}
DART_KEYWORDS = {
    "abstract",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "covariant",
    "default",
    "deferred",
    "do",
    "dynamic",
    "else",
    "enum",
    "export",
    "extends",
    "extension",
    "external",
    "factory",
    "false",
    "final",
    "for",
    "get",
    "hide",
    "if",
    "implements",
    "import",
    "in",
    "interface",
    "is",
    "late",
    "library",
    "mixin",
    "new",
    "null",
    "of",
    "on",
    "operator",
    "part",
    "required",
    "rethrow",
    "return",
    "set",
    "show",
    "static",
    "super",
    "switch",
    "sync",
    "this",
    "throw",
    "true",
    "try",
    "typedef",
    "var",
    "void",
    "when",
    "while",
    "with",
    "yield",
}
IGNORED_SCHEMA_KEYS = {"description", "title", "example", "examples", "deprecated"}


@dataclass(frozen=True)
class WrapperUse:
    """One concrete OpenAPI schema represented by a generic Dart wrapper."""

    rule: DartGenericWrapperRule
    payload_schema: dict[str, Any]


@dataclass(frozen=True)
class WrapperModel:
    """One generic wrapper class to render for an OpenAPI document."""

    rule: DartGenericWrapperRule
    schema: dict[str, Any]


def pascal(value: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", value)
    rendered = "".join(part[:1].upper() + part[1:] for part in parts) or "Value"
    return f"Api{rendered}" if rendered[0].isdigit() else rendered


def camel(value: str) -> str:
    rendered = pascal(value)
    return rendered[:1].lower() + rendered[1:]


def file_stem(path: Path) -> str:
    return path.name.removesuffix(".openapi.json")


def valid_identifier(value: str) -> str:
    candidate = camel(value)
    if candidate in DART_KEYWORDS:
        candidate += "Value"
    return candidate if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", candidate) else "value"


def raw_ref_name(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
        return unquote(ref.rsplit("/", 1)[1])
    return None


def ref_name(schema: dict[str, Any]) -> str | None:
    name = raw_ref_name(schema)
    return pascal(name) if name else None


def dart_type(
    schema: dict[str, Any] | None,
    wrappers: dict[str, WrapperUse] | None = None,
) -> str:
    if not schema:
        return "dynamic"
    raw_name = raw_ref_name(schema)
    if raw_name and wrappers and raw_name in wrappers:
        wrapper = wrappers[raw_name]
        payload = dart_type(wrapper.payload_schema, wrappers)
        return f"{wrapper.rule.dart_name}<{payload}>"
    if name := ref_name(schema):
        return name
    if "allOf" in schema:
        for item in schema["allOf"]:
            if isinstance(item, dict):
                resolved = dart_type(item, wrappers)
                if resolved != "dynamic":
                    return resolved
    schema_type = schema.get("type")
    if schema_type == "string":
        return "DateTime" if schema.get("format") in {"date", "date-time"} else "String"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "double"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "array":
        return f"List<{dart_type(schema.get('items'), wrappers)}>"
    if schema_type == "object" or "additionalProperties" in schema:
        additional = schema.get("additionalProperties")
        value_type = (
            dart_type(additional, wrappers)
            if isinstance(additional, dict)
            else "dynamic"
        )
        return f"Map<String, {value_type}>"
    return "dynamic"


def property_schemas(schema: dict[str, Any]) -> dict[str, dict[str, Any]]:
    properties: dict[str, dict[str, Any]] = {}
    for item in schema.get("allOf", []):
        if isinstance(item, dict):
            properties.update(property_schemas(item))
    raw = schema.get("properties", {})
    if isinstance(raw, dict):
        properties.update(
            {key: value for key, value in raw.items() if isinstance(value, dict)}
        )
    return properties


def normalized_schema(value: Any) -> Any:
    """Remove descriptive metadata while retaining wire-significant structure."""

    if isinstance(value, dict):
        return {
            key: normalized_schema(item)
            for key, item in sorted(value.items())
            if key not in IGNORED_SCHEMA_KEYS
        }
    if isinstance(value, list):
        return [normalized_schema(item) for item in value]
    return value


def wrapper_signature(schema: dict[str, Any], type_parameter_field: str) -> Any:
    normalized = normalized_schema(schema)
    properties = normalized.get("properties")
    if not isinstance(properties, dict) or type_parameter_field not in properties:
        raise ValueError(
            f"generic wrapper is missing property {type_parameter_field!r}"
        )
    properties[type_parameter_field] = {"$generic": "T"}
    return normalized


def build_wrapper_models(
    schemas: dict[str, Any],
    rules: tuple[DartGenericWrapperRule, ...],
) -> tuple[dict[str, WrapperUse], list[WrapperModel]]:
    uses: dict[str, WrapperUse] = {}
    models: list[WrapperModel] = []
    for rule in rules:
        matches = [
            (name, schema)
            for name, schema in schemas.items()
            if isinstance(schema, dict) and fnmatchcase(name, rule.schema_glob)
        ]
        if not matches:
            continue
        first_name, first_schema = matches[0]
        first_properties = property_schemas(first_schema)
        if rule.type_parameter_field not in first_properties:
            raise ValueError(
                f"generic wrapper rule {rule.rule_name!r} matched {first_name!r}, "
                f"which has no {rule.type_parameter_field!r} property"
            )
        expected = wrapper_signature(first_schema, rule.type_parameter_field)
        for schema_name, schema in matches:
            if schema_name in uses:
                other = uses[schema_name].rule.rule_name
                raise ValueError(
                    f"OpenAPI schema {schema_name!r} matches generic wrapper rules "
                    f"{other!r} and {rule.rule_name!r}"
                )
            properties = property_schemas(schema)
            payload = properties.get(rule.type_parameter_field)
            if payload is None:
                raise ValueError(
                    f"generic wrapper rule {rule.rule_name!r} matched {schema_name!r}, "
                    f"which has no {rule.type_parameter_field!r} property"
                )
            if wrapper_signature(schema, rule.type_parameter_field) != expected:
                raise ValueError(
                    f"OpenAPI schemas {first_name!r} and {schema_name!r} matched "
                    f"generic wrapper rule {rule.rule_name!r} but differ outside "
                    f"property {rule.type_parameter_field!r}"
                )
            uses[schema_name] = WrapperUse(rule=rule, payload_schema=payload)
        models.append(WrapperModel(rule=rule, schema=first_schema))

    ordinary_names = {
        pascal(name)
        for name, schema in schemas.items()
        if isinstance(schema, dict) and name not in uses
    }
    for model in models:
        if model.rule.dart_name in ordinary_names:
            raise ValueError(
                f"generic wrapper Dart name {model.rule.dart_name!r} conflicts "
                "with an ordinary OpenAPI schema"
            )
    return uses, models


def model_fields(
    schema: dict[str, Any],
    wrappers: dict[str, WrapperUse],
) -> list[tuple[str, str, str]]:
    fields: list[tuple[str, str, str]] = []
    for json_name, property_schema in property_schemas(schema).items():
        fields.append(
            (
                json_name,
                valid_identifier(json_name),
                dart_type(property_schema, wrappers),
            )
        )
    return fields


def render_model(
    name: str,
    schema: dict[str, Any],
    wrappers: dict[str, WrapperUse],
) -> list[str]:
    class_name = pascal(name)
    fields = model_fields(schema, wrappers)
    lines = ["@JsonSerializable(explicitToJson: true)", f"class {class_name} {{"]
    if fields:
        lines.append(f"  const {class_name}({{")
        for _, field_name, _ in fields:
            lines.append(f"    this.{field_name},")
        lines.append("  });")
    else:
        lines.append(f"  const {class_name}();")
    lines.extend(
        [
            "",
            f"  factory {class_name}.fromJson(Map<String, dynamic> json) =>",
            f"      _${class_name}FromJson(json);",
        ]
    )
    for json_name, field_name, field_type in fields:
        if field_name != json_name:
            lines.append(f"  @JsonKey(name: {json.dumps(json_name)})")
        nullable_type = field_type if field_type == "dynamic" else f"{field_type}?"
        lines.append(f"  final {nullable_type} {field_name};")
    lines.extend(
        [
            "",
            f"  Map<String, dynamic> toJson() => _${class_name}ToJson(this);",
            "}",
            "",
        ]
    )
    return lines


def render_wrapper_model(
    model: WrapperModel,
    wrappers: dict[str, WrapperUse],
) -> list[str]:
    rule = model.rule
    fields = model_fields(model.schema, wrappers)
    lines = [
        "@JsonSerializable(explicitToJson: true, genericArgumentFactories: true)",
        f"class {rule.dart_name}<T> {{",
        f"  const {rule.dart_name}({{",
    ]
    for _, field_name, _ in fields:
        lines.append(f"    this.{field_name},")
    lines.extend(
        [
            "  });",
            "",
            f"  factory {rule.dart_name}.fromJson(",
            "    Map<String, dynamic> json,",
            "    T Function(Object? json) fromJsonT,",
            f"  ) => _${rule.dart_name}FromJson(json, fromJsonT);",
        ]
    )
    for json_name, field_name, field_type in fields:
        if field_name != json_name:
            lines.append(f"  @JsonKey(name: {json.dumps(json_name)})")
        if json_name == rule.type_parameter_field:
            lines.append(f"  final T? {field_name};")
        else:
            nullable_type = field_type if field_type == "dynamic" else f"{field_type}?"
            lines.append(f"  final {nullable_type} {field_name};")
    lines.extend(
        [
            "",
            "  Map<String, dynamic> toJson(",
            "    Object? Function(T value) toJsonT,",
            f"  ) => _${rule.dart_name}ToJson(this, toJsonT);",
            "}",
            "",
        ]
    )
    return lines


def schema_from_content(content: Any) -> dict[str, Any] | None:
    if not isinstance(content, dict):
        return None
    for media in content.values():
        if isinstance(media, dict) and isinstance(media.get("schema"), dict):
            return media["schema"]
    return None


def multipart_arguments(content: Any) -> list[str] | None:
    """Render Retrofit parts when the OpenAPI request body is multipart."""
    if not isinstance(content, dict):
        return None
    media = content.get("multipart/form-data")
    if not isinstance(media, dict):
        return None
    schema = media.get("schema")
    if not isinstance(schema, dict):
        return []
    properties = schema.get("properties", {})
    if not isinstance(properties, dict):
        return []
    required = set(schema.get("required", []))
    arguments: list[str] = []
    for property_name, property_schema in properties.items():
        if not isinstance(property_name, str) or not isinstance(property_schema, dict):
            continue
        if (
            property_schema.get("type") == "string"
            and property_schema.get("format") == "binary"
        ):
            property_type = "MultipartFile"
        elif property_schema.get("type") == "array":
            items = property_schema.get("items")
            property_type = (
                "List<MultipartFile>"
                if isinstance(items, dict)
                and items.get("type") == "string"
                and items.get("format") == "binary"
                else dart_type(property_schema)
            )
        else:
            property_type = dart_type(property_schema)
        if property_name not in required:
            property_type += "?"
        arguments.append(
            f"    @Part(name: {json.dumps(property_name)}) "
            f"{property_type} {valid_identifier(property_name)},"
        )
    return arguments


def operation_name(
    method: str,
    path: str,
    operation: dict[str, Any],
    used: set[str],
) -> str:
    base = (
        operation.get("operationId")
        if isinstance(operation.get("operationId"), str)
        else None
    )
    if not base:
        base = method.lower() + " " + path.replace("{", "by ").replace("}", "")
    candidate = valid_identifier(base)
    suffix = 2
    original = candidate
    while candidate in used:
        candidate = f"{original}{suffix}"
        suffix += 1
    used.add(candidate)
    return candidate


def render_operation(
    method: str,
    path: str,
    operation: dict[str, Any],
    used: set[str],
    wrappers: dict[str, WrapperUse],
) -> list[str]:
    name = operation_name(method, path, operation, used)
    response_schema = None
    responses = operation.get("responses", {})
    if isinstance(responses, dict):
        for status, response in responses.items():
            if str(status).startswith("2") and isinstance(response, dict):
                response_schema = schema_from_content(response.get("content"))
                break
    response_type = dart_type(response_schema, wrappers) if response_schema else "void"
    parameters = operation.get("parameters", [])
    arguments: list[str] = []
    if isinstance(parameters, list):
        for parameter in parameters:
            if not isinstance(parameter, dict) or not isinstance(
                parameter.get("name"), str
            ):
                continue
            parameter_name = parameter["name"]
            annotation = {"path": "Path", "query": "Query", "header": "Header"}.get(
                parameter.get("in")
            )
            if annotation:
                arguments.append(
                    f"    @{annotation}({json.dumps(parameter_name)}) "
                    f"{dart_type(parameter.get('schema'), wrappers)} "
                    f"{valid_identifier(parameter_name)},"
                )
    request_body = operation.get("requestBody")
    content = request_body.get("content") if isinstance(request_body, dict) else None
    parts = multipart_arguments(content)
    if parts is not None:
        arguments.extend(parts)
    else:
        body = schema_from_content(content)
        if body:
            arguments.append(f"    @Body() {dart_type(body, wrappers)} body,")
    rendered_path = re.sub(r"\{([^}]+)\}", r"{\1}", path)
    annotations = []
    if parts is not None:
        annotations.append("  @MultiPart()")
    annotations.append(f"  @{method.upper()}({json.dumps(rendered_path)})")
    lines = [
        *annotations,
        f"  Future<{response_type}> {name}(",
    ]
    lines.extend(arguments)
    lines.append("  );")
    return lines


def render_document(
    document: dict[str, Any],
    source: Path,
    rules: tuple[DartGenericWrapperRule, ...],
) -> str:
    schemas = document.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        schemas = {}
    wrappers, wrapper_models = build_wrapper_models(schemas, rules)
    class_name = pascal(file_stem(source)) + "Api"
    lines = [
        MARKER,
        f"// Source: {source.as_posix()}",
        "import 'package:dio/dio.dart';",
        "import 'package:json_annotation/json_annotation.dart';",
        "import 'package:retrofit/retrofit.dart';",
        "",
        f"part '{file_stem(source)}_api.g.dart';",
        "",
        "@RestApi()",
        f"abstract class {class_name} {{",
        f"  factory {class_name}(Dio dio, {{String? baseUrl}}) = _{class_name};",
        "",
    ]
    used: set[str] = set()
    paths = document.get("paths", {})
    if isinstance(paths, dict):
        for path, path_item in paths.items():
            if not isinstance(path_item, dict):
                continue
            for method, operation in path_item.items():
                if method.lower() in HTTP_METHODS and isinstance(operation, dict):
                    lines.extend(
                        render_operation(method, path, operation, used, wrappers)
                    )
                    lines.append("")
    lines.extend(["}", ""])
    for model in wrapper_models:
        lines.extend(render_wrapper_model(model, wrappers))
    for name, schema in schemas.items():
        if isinstance(schema, dict) and name not in wrappers:
            lines.extend(render_model(name, schema, wrappers))
    return "\n".join(lines)


def format_dart(source: str) -> str:
    """Use the project's FVM formatter so generated files are drift-free."""

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".dart", encoding="utf-8"
    ) as temporary:
        temporary.write(source)
        temporary.flush()
        result = subprocess.run(
            [
                os.environ.get("FR_MVVM_FVM", "fvm"),
                "dart",
                "format",
                "--output=show",
                temporary.name,
            ],
            capture_output=True,
            text=True,
            check=False,
        )
    if result.returncode:
        raise ValueError(f"Dart formatter failed: {result.stderr.strip()}")
    return re.sub(r"\n?Formatted .*?\n?$", "", result.stdout).rstrip() + "\n"


def input_files(source: Path) -> list[Path]:
    return [source] if source.is_file() else sorted(source.glob("*.openapi.json"))


def stale_output_files(source: Path, output: Path, expected: set[Path]) -> list[Path]:
    """Return generated SDK files whose OpenAPI source no longer exists."""

    if source.is_file() or not output.is_dir():
        return []
    stale: list[Path] = []
    for target in sorted(output.glob("*_api.dart")):
        if target in expected:
            continue
        existing = target.read_text(encoding="utf-8")
        if not existing.startswith((MARKER, LEGACY_MARKER)):
            continue
        stale.append(target)
        generated_part = target.with_name(f"{target.stem}.g.dart")
        if generated_part.is_file():
            part_source = generated_part.read_text(encoding="utf-8")
            if (
                part_source.startswith(BUILD_RUNNER_MARKER)
                and f"part of '{target.name}';" in part_source
            ):
                stale.append(generated_part)
    return stale


def generate(
    source: Path,
    output: Path,
    *,
    check: bool,
    rules: tuple[DartGenericWrapperRule, ...],
) -> list[Path]:
    files = input_files(source)
    if not files:
        raise ValueError(f"no .openapi.json files found under {source}")
    expected = {output / f"{file_stem(input_file)}_api.dart" for input_file in files}
    changed: list[Path] = []
    for input_file in files:
        document = json.loads(input_file.read_text(encoding="utf-8"))
        if not isinstance(document, dict) or not isinstance(
            document.get("openapi"), str
        ):
            raise ValueError(f"invalid OpenAPI document: {input_file}")
        target = output / f"{file_stem(input_file)}_api.dart"
        rendered = format_dart(render_document(document, input_file, rules))
        existing = target.read_text(encoding="utf-8") if target.exists() else None
        if existing != rendered:
            changed.append(target)
            if not check:
                if existing is not None and not existing.startswith(
                    (MARKER, LEGACY_MARKER)
                ):
                    raise ValueError(
                        f"refusing to overwrite non-generated file: {target}"
                    )
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(rendered, encoding="utf-8")
    stale = stale_output_files(source, output, expected)
    changed.extend(stale)
    if not check:
        for target in stale:
            target.unlink()
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path("docs/openapi"))
    parser.add_argument("--output", type=Path, default=Path("lib/api/gen"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        rules = load_dart_generic_wrapper_rules(Path.cwd())
        changed = generate(args.source, args.output, check=args.check, rules=rules)
    except (OSError, ValueError, ResolveError, json.JSONDecodeError) as error:
        parser.error(str(error))
    if changed:
        print(
            f"OpenAPI Retrofit generation "
            f"{'would change' if args.check else 'changed'}: {len(changed)} files"
        )
        print("\n".join(str(path) for path in changed))
        return 1 if args.check else 0
    print("OpenAPI Retrofit generation is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
