name: flowr
description: "FlowR: state management package for the MVVM pattern based on reactive programming."
version: 0.3.0
homepage: "https://github.com/Hu-Wentao/flowr"

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.7 # fixed; "8.0.0-pre-1" is "7.6.7+1", use 'getAll';
  injectable: ^2.3.5 # fixed; adapt flutter 3.16.7;
  provider: ^6.1.5
  rxdart: ^0.27.7 # fixed; adapt flutter 3.16.7;
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # fixed; adapt flutter 3.16.7


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


