name: flowr
description: "FlowR: state management package for the MVVM pattern based on reactive programming."
version: 0.19.1
homepage: "https://github.com/Hu-Wentao/flowr"

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # --- FlowR ---
  rxdart: ^0.27.7 # fixed; adapt flutter 3.16.7;
  # --- FlowR-MVVM ---
  get_it: ^7.6.7 # fixed; "8.0.0-pre-1" is "7.6.7+1", use 'getAll';
  injectable: ^2.3.5 # fixed; adapt flutter 3.16.7;
  provider: ^6.1.5
  stack_trace: ^1.11.1
  # --- FlowR-Arch ---
  sembast: ^3.6.0 # fixed; adapt flutter 3.16.7;
  path: ^1.8.3 # fixed; adapt flutter 3.16.7;
  path_provider: ^2.1.4 # fixed; adapt flutter 3.16.7;
  ulid: ^2.0.1 # fixed; adapt flutter 3.16.7;
  async: ^2.11.0 # fixed; adapt flutter 3.16.7;
  slowly: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # fixed; adapt flutter 3.16.7

#dependency_overrides:
#  slowly:
#    path: ../slowly
#    git:
#      url: https://github.com/Hu-Wentao/slowly.git
#      ref: main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


