name: _
publish_to: none
environment:
  sdk: ^3.7.0
workspace:
  - examples/example
  - packages/flowr_dart
  - packages/flowr
  - packages/fr_mvvm_env
  - packages/fr_mvvm_env/example
  - packages/fr_mvvm_locale
  - packages/fr_mvvm_locale/example
  - packages/fr_mvvm_theme
  - packages/fr_mvvm_theme/example
  - packages/fr_mvvm_user
  - packages/fr_mvvm_user/example
