name: _
publish_to: none
environment:
  sdk: ^3.7.0
workspace:
  - packages/flowr_dart
  - packages/flowr
  - packages/flowr_arch
  - packages/fr_mvvm_env
  - packages/fr_mvvm_env/example
  - examples/example
  - examples/quick_start_mvvm