name: example_fr_storage
description: Example application for fr_storage.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  fr_storage:

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
