name: fr_mvvm_user
description: "FlowR-MVVM: User"
version: 2.0.0
repository: "https://github.com/Hu-Wentao/flowr"
topics:
  - flowr
  - user-management

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flowr: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
