name: flowr_dart
description: "Base FlowR library for pure Dart"
version: 1.0.0
homepage: "https://github.com/Hu-Wentao/flowr"

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  async: ^2.11.0
  rxdart: ^0.27.7
  stack_trace: ^1.11.1
  slowly: ^0.3.0

dev_dependencies:
  test: ^1.25.0