import '../enums/fr_acdd_dto_kind.dart';
import '../model/extracted_contract_schema.dart';
import '../model/extracted_dto_schema.dart';
import '../model/extracted_field_schema.dart';

class Json5SchemaBuilder {
  const Json5SchemaBuilder();

  String build(ExtractedContractSchema schema) {
    if (!schema.supported) {
      throw StateError(
        schema.reason ?? 'The contract does not support BFF DTO export.',
      );
    }

    final dtoByName = {for (final dto in schema.dtos) dto.name: dto};
    final roots = schema.dtos
        .where((dto) => dto.kind == FrAcddDtoKind.root)
        .toList(growable: false);

    final buffer =
        StringBuffer()
          ..writeln('// Generated by fr_acdd. Do not edit by hand.')
          ..writeln('// Source: ${schema.source}');
    if (schema.routePath != null) {
      buffer.writeln('// Route: ${schema.routePath}');
    }
    if (schema.figmaReference != null) {
      buffer.writeln('// Figma: ${schema.figmaReference}');
    }
    if (schema.apis.isNotEmpty) {
      buffer.writeln(
        schema.apis.length == 1
            ? '// Suggested API path:'
            : '// Suggested API paths:',
      );
      for (final api in schema.apis) {
        buffer.writeln('// - ${api.suggestedPath}: ${api.description}');
      }
    }
    buffer.writeln('// JSON5 payload shape:');

    final payloadLines =
        roots.length == 1
            ? _renderDtoObject(
              roots.single,
              dtoByName: dtoByName,
              propertyIndent: 0,
              activeTypes: const {},
            )
            : _renderMultiRootObject(roots, dtoByName: dtoByName);
    buffer.write(payloadLines.join('\n'));
    buffer.writeln();
    return buffer.toString();
  }

  List<String> _renderMultiRootObject(
    List<ExtractedDtoSchema> roots, {
    required Map<String, ExtractedDtoSchema> dtoByName,
  }) {
    final lines = <String>['{'];
    for (final root in roots) {
      lines.add('  // ${root.name}');
      final value = _renderDtoObject(
        root,
        dtoByName: dtoByName,
        propertyIndent: 2,
        activeTypes: const {},
      );
      _appendMultilineField(
        lines,
        indent: 2,
        key: _topLevelKey(root.name),
        value: value,
      );
    }
    lines.add('}');
    return lines;
  }

  List<String> _renderDtoObject(
    ExtractedDtoSchema dto, {
    required Map<String, ExtractedDtoSchema> dtoByName,
    required int propertyIndent,
    required Set<String> activeTypes,
  }) {
    final prefix = ' ' * propertyIndent;
    final fieldIndent = propertyIndent + 2;
    if (activeTypes.contains(dto.name)) {
      return [
        '{',
        '${' ' * fieldIndent}// Circular reference to ${dto.name}',
        '$prefix}',
      ];
    }

    final lines = <String>['{'];
    final nextActiveTypes = {...activeTypes, dto.name};
    for (final field in dto.fields) {
      for (final comment in _fieldCommentLines(field)) {
        lines.add('${' ' * fieldIndent}// $comment');
      }
      final value = _renderFieldValue(
        field,
        dtoByName: dtoByName,
        propertyIndent: fieldIndent,
        activeTypes: nextActiveTypes,
      );
      _appendMultilineField(
        lines,
        indent: fieldIndent,
        key: field.wireName,
        value: value,
      );
    }
    lines.add('$prefix}');
    return lines;
  }

  List<String> _renderFieldValue(
    ExtractedFieldSchema field, {
    required Map<String, ExtractedDtoSchema> dtoByName,
    required int propertyIndent,
    required Set<String> activeTypes,
  }) {
    switch (field.normalizedType) {
      case 'string':
        return const ["'string'"];
      case 'int':
      case 'double':
      case 'num':
        return const ['0'];
      case 'bool':
        return const ['false'];
      case 'datetime':
        return const ["'2026-01-01T00:00:00Z'"];
      case 'enum':
        return const ["'enum-value'"];
      case 'object':
        return _renderNestedDto(
          field,
          dtoByName: dtoByName,
          propertyIndent: propertyIndent,
          activeTypes: activeTypes,
        );
      case 'list':
      case 'set':
        return _renderCollectionValue(
          field,
          dtoByName: dtoByName,
          propertyIndent: propertyIndent,
          activeTypes: activeTypes,
        );
      case 'map':
        return _renderMapValue(
          field,
          dtoByName: dtoByName,
          propertyIndent: propertyIndent,
          activeTypes: activeTypes,
        );
      default:
        throw StateError(
          'Unsupported normalized type `${field.normalizedType}` on `${field.name}`.',
        );
    }
  }

  List<String> _renderNestedDto(
    ExtractedFieldSchema field, {
    required Map<String, ExtractedDtoSchema> dtoByName,
    required int propertyIndent,
    required Set<String> activeTypes,
  }) {
    final nestedDto = dtoByName[field.nestedRef];
    if (nestedDto == null) {
      return const ['{}'];
    }
    return _renderDtoObject(
      nestedDto,
      dtoByName: dtoByName,
      propertyIndent: propertyIndent,
      activeTypes: activeTypes,
    );
  }

  List<String> _renderCollectionValue(
    ExtractedFieldSchema field, {
    required Map<String, ExtractedDtoSchema> dtoByName,
    required int propertyIndent,
    required Set<String> activeTypes,
  }) {
    if (field.itemNormalizedType == null) {
      return const ['[]'];
    }
    final itemIndent = propertyIndent + 2;
    final itemValue = _renderCollectionItemValue(
      field,
      dtoByName: dtoByName,
      propertyIndent: itemIndent,
      activeTypes: activeTypes,
    );
    if (itemValue.length == 1) {
      return ['[${itemValue.single}]'];
    }
    final lines = <String>['['];
    lines.add('${' ' * itemIndent}${itemValue.first}');
    if (itemValue.length > 2) {
      lines.addAll(itemValue.sublist(1, itemValue.length - 1));
    }
    lines.add('${itemValue.last},');
    lines.add('${' ' * propertyIndent}]');
    return lines;
  }

  List<String> _renderCollectionItemValue(
    ExtractedFieldSchema field, {
    required Map<String, ExtractedDtoSchema> dtoByName,
    required int propertyIndent,
    required Set<String> activeTypes,
  }) {
    switch (field.itemNormalizedType) {
      case 'string':
        return const ["'string'"];
      case 'int':
      case 'double':
      case 'num':
        return const ['0'];
      case 'bool':
        return const ['false'];
      case 'datetime':
        return const ["'2026-01-01T00:00:00Z'"];
      case 'enum':
        return const ["'enum-value'"];
      case 'object':
        return _renderNestedDto(
          field,
          dtoByName: dtoByName,
          propertyIndent: propertyIndent,
          activeTypes: activeTypes,
        );
      default:
        throw StateError(
          'Unsupported collection item type `${field.itemType}` on `${field.name}`.',
        );
    }
  }

  List<String> _renderMapValue(
    ExtractedFieldSchema field, {
    required Map<String, ExtractedDtoSchema> dtoByName,
    required int propertyIndent,
    required Set<String> activeTypes,
  }) {
    final key = _placeholderMapKey(field);
    final valueIndent = propertyIndent + 2;
    final mapValue = _renderMapItemValue(
      field,
      dtoByName: dtoByName,
      propertyIndent: valueIndent,
      activeTypes: activeTypes,
    );
    if (mapValue.length == 1) {
      return ['{$key: ${mapValue.single}}'];
    }
    final lines = <String>['{'];
    lines.add('${' ' * valueIndent}$key: ${mapValue.first}');
    if (mapValue.length > 2) {
      lines.addAll(mapValue.sublist(1, mapValue.length - 1));
    }
    lines.add('${mapValue.last},');
    lines.add('${' ' * propertyIndent}}');
    return lines;
  }

  List<String> _renderMapItemValue(
    ExtractedFieldSchema field, {
    required Map<String, ExtractedDtoSchema> dtoByName,
    required int propertyIndent,
    required Set<String> activeTypes,
  }) {
    switch (field.mapValueNormalizedType) {
      case 'string':
        return const ["'string'"];
      case 'int':
      case 'double':
      case 'num':
        return const ['0'];
      case 'bool':
        return const ['false'];
      case 'datetime':
        return const ["'2026-01-01T00:00:00Z'"];
      case 'enum':
        return const ["'enum-value'"];
      case 'object':
        return _renderNestedDto(
          field,
          dtoByName: dtoByName,
          propertyIndent: propertyIndent,
          activeTypes: activeTypes,
        );
      default:
        throw StateError(
          'Unsupported map item type `${field.mapValueType}` on `${field.name}`.',
        );
    }
  }

  void _appendMultilineField(
    List<String> lines, {
    required int indent,
    required String key,
    required List<String> value,
  }) {
    final prefix = ' ' * indent;
    final renderedKey = _json5Key(key);
    if (value.length == 1) {
      lines.add('$prefix$renderedKey: ${value.single},');
      return;
    }
    lines.add('$prefix$renderedKey: ${value.first}');
    if (value.length > 2) {
      lines.addAll(value.sublist(1, value.length - 1));
    }
    lines.add('${value.last},');
  }

  List<String> _fieldCommentLines(ExtractedFieldSchema field) {
    final lines = <String>['Dart type: ${field.dartType}'];
    if (field.nestedRef != null) {
      lines.add('Nested DTO: ${field.nestedRef}');
    }
    if (field.defaultCode != null) {
      lines.add('Default: ${field.defaultCode}');
    }
    return lines;
  }

  String _placeholderMapKey(ExtractedFieldSchema field) {
    switch (field.mapKeyNormalizedType) {
      case 'int':
        return '0';
      default:
        return _json5Key('key');
    }
  }

  String _json5Key(String key) {
    if (RegExp(r'^[A-Za-z_$][A-Za-z0-9_$]*$').hasMatch(key)) {
      return key;
    }
    return "'${key.replaceAll("'", "\\'")}'";
  }

  String _topLevelKey(String dtoName) {
    final trimmed =
        dtoName.endsWith('Model')
            ? dtoName.substring(0, dtoName.length - 5)
            : dtoName;
    if (trimmed.isEmpty) {
      return 'payload';
    }
    return '${trimmed[0].toLowerCase()}${trimmed.substring(1)}';
  }
}
