import '../enums/fr_acdd_dto_kind.dart';
import '../model/extracted_api_schema.dart';
import '../model/extracted_contract_schema.dart';
import '../model/extracted_dto_schema.dart';
import '../model/extracted_field_schema.dart';

class ProtoSchemaBuilder {
  const ProtoSchemaBuilder();

  String build(ExtractedContractSchema schema) {
    if (!schema.supported) {
      throw StateError(
        schema.reason ?? 'The contract does not support BFF export.',
      );
    }

    final dtos = _orderedDtos(schema.dtos);
    final needsTimestamp = dtos.any((dto) => dto.fields.any(_needsTimestamp));
    final buffer =
        StringBuffer()
          ..writeln('// Generated by fr_acdd. Do not edit by hand.')
          ..writeln('// Source: ${schema.source}');
    if (schema.routePath != null) {
      buffer.writeln('// Route: ${schema.routePath}');
    }
    if (schema.figmaReference != null) {
      buffer.writeln('// Figma: ${schema.figmaReference}');
    }
    if (schema.apis.isNotEmpty) {
      buffer.writeln('// BFF-API:');
      for (final api in schema.apis) {
        buffer.writeln('// - ${api.method} ${api.suggestedPath}');
        final refsLine = _apiRefsLine(api);
        if (refsLine != null) {
          buffer.writeln('//   $refsLine');
        }
      }
    }
    buffer
      ..writeln('syntax = "proto3";')
      ..writeln()
      ..writeln('package ${_packageName(schema.namespace, schema.version)};');

    if (needsTimestamp) {
      buffer
        ..writeln()
        ..writeln('import "google/protobuf/timestamp.proto";');
    }

    for (final dto in dtos) {
      buffer
        ..writeln()
        ..writeln(_messageBlock(dto));
    }

    return buffer.toString();
  }

  Iterable<ExtractedDtoSchema> _orderedDtos(List<ExtractedDtoSchema> dtos) {
    final rootDtos = dtos.where((dto) => dto.kind == FrAcddDtoKind.root);
    final nestedDtos = dtos.where((dto) => dto.kind == FrAcddDtoKind.nested);
    return [...rootDtos, ...nestedDtos];
  }

  bool _needsTimestamp(ExtractedFieldSchema field) {
    return field.normalizedType == 'datetime' ||
        field.itemNormalizedType == 'datetime' ||
        field.mapValueNormalizedType == 'datetime';
  }

  String _messageBlock(ExtractedDtoSchema dto) {
    final lines = <String>[];
    if (dto.description != null) {
      lines.add('// ${dto.description}');
    }
    lines.add('// DTO kind: ${dto.kind.name}');
    lines.add('message ${_validatedIdentifier(dto.name, label: 'DTO name')} {');

    final fields = [...dto.fields]..sort((left, right) {
      final leftTag = left.tag ?? 1 << 30;
      final rightTag = right.tag ?? 1 << 30;
      return leftTag.compareTo(rightTag);
    });
    _validateFieldTags(dto, fields);

    for (final field in fields) {
      for (final line in _fieldCommentLines(field)) {
        lines.add('  // $line');
      }
      lines.add('  ${_fieldDeclaration(field)}');
    }

    lines.add('}');
    return lines.join('\n');
  }

  void _validateFieldTags(
    ExtractedDtoSchema dto,
    List<ExtractedFieldSchema> fields,
  ) {
    final seenTags = <int>{};
    for (final field in fields) {
      final tag = field.tag;
      if (tag == null) {
        throw StateError(
          'Field `${dto.name}.${field.name}` is missing @FrAcddField(tag: ...).',
        );
      }
      if (tag <= 0) {
        throw StateError(
          'Field `${dto.name}.${field.name}` uses invalid tag `$tag`.',
        );
      }
      if (tag >= 19000 && tag <= 19999) {
        throw StateError(
          'Field `${dto.name}.${field.name}` uses reserved protobuf tag `$tag`.',
        );
      }
      if (!seenTags.add(tag)) {
        throw StateError(
          'DTO `${dto.name}` contains duplicate protobuf tag `$tag`.',
        );
      }
    }
  }

  List<String> _fieldCommentLines(ExtractedFieldSchema field) {
    final lines = <String>['Dart type: ${field.dartType}'];
    if (field.wireName != field.name) {
      lines.add('Dart field: ${field.name}');
    }
    if (field.defaultCode != null) {
      lines.add('Default: ${field.defaultCode}');
    }
    return lines;
  }

  String _fieldDeclaration(ExtractedFieldSchema field) {
    final prefix = _fieldPrefix(field);
    final type = _fieldType(field);
    final fieldName = _validatedIdentifier(field.wireName, label: 'Field name');
    final prefixText = prefix.isEmpty ? '' : '$prefix ';
    return '$prefixText$type $fieldName = ${field.tag};';
  }

  String _fieldPrefix(ExtractedFieldSchema field) {
    if (field.normalizedType == 'list' || field.normalizedType == 'set') {
      return 'repeated';
    }
    if (field.normalizedType == 'map') {
      return '';
    }
    if (field.nullable && _supportsProtoOptional(field.normalizedType)) {
      return 'optional';
    }
    return '';
  }

  bool _supportsProtoOptional(String normalizedType) {
    switch (normalizedType) {
      case 'string':
      case 'int':
      case 'double':
      case 'num':
      case 'bool':
      case 'enum':
        return true;
      default:
        return false;
    }
  }

  String _fieldType(ExtractedFieldSchema field) {
    switch (field.normalizedType) {
      case 'string':
        return 'string';
      case 'int':
        return 'int64';
      case 'double':
      case 'num':
        return 'double';
      case 'bool':
        return 'bool';
      case 'datetime':
        return 'google.protobuf.Timestamp';
      case 'enum':
        return 'string';
      case 'object':
        return _requireNestedRef(field);
      case 'list':
      case 'set':
        return _collectionItemType(field);
      case 'map':
        return 'map<${_mapKeyType(field)}, ${_mapValueType(field)}>';
      default:
        throw StateError(
          'Unsupported normalized type `${field.normalizedType}` on `${field.name}`.',
        );
    }
  }

  String _collectionItemType(ExtractedFieldSchema field) {
    switch (field.itemNormalizedType) {
      case 'string':
        return 'string';
      case 'int':
        return 'int64';
      case 'double':
      case 'num':
        return 'double';
      case 'bool':
        return 'bool';
      case 'datetime':
        return 'google.protobuf.Timestamp';
      case 'enum':
        return 'string';
      case 'object':
        return _requireNestedRef(field);
      default:
        throw StateError(
          'Unsupported collection item type `${field.itemType}` on `${field.name}`.',
        );
    }
  }

  String _mapKeyType(ExtractedFieldSchema field) {
    switch (field.mapKeyNormalizedType) {
      case 'string':
        return 'string';
      case 'int':
        return 'int64';
      case 'bool':
        return 'bool';
      default:
        throw StateError(
          'Map field `${field.name}` uses unsupported key type `${field.mapKeyType}`.',
        );
    }
  }

  String _mapValueType(ExtractedFieldSchema field) {
    switch (field.mapValueNormalizedType) {
      case 'string':
        return 'string';
      case 'int':
        return 'int64';
      case 'double':
      case 'num':
        return 'double';
      case 'bool':
        return 'bool';
      case 'datetime':
        return 'google.protobuf.Timestamp';
      case 'enum':
        return 'string';
      case 'object':
        return _requireNestedRef(field);
      default:
        throw StateError(
          'Map field `${field.name}` uses unsupported value type `${field.mapValueType}`.',
        );
    }
  }

  String _requireNestedRef(ExtractedFieldSchema field) {
    final nestedRef = field.nestedRef;
    if (nestedRef == null || nestedRef.isEmpty) {
      throw StateError(
        'Field `${field.name}` requires a nested DTO reference but none was found.',
      );
    }
    return _validatedIdentifier(nestedRef, label: 'Nested DTO name');
  }

  String _packageName(String namespace, int version) {
    final rawSegments = namespace
        .split('.')
        .map((segment) => segment.trim())
        .where((segment) => segment.isNotEmpty)
        .toList(growable: false);
    final segments = rawSegments.isEmpty ? const ['fr_acdd'] : rawSegments;
    final normalized = [
      for (final segment in segments) _sanitizePackageSegment(segment),
      'v$version',
    ];
    return normalized.join('.');
  }

  String _sanitizePackageSegment(String segment) {
    final lower = segment.toLowerCase().replaceAll(RegExp(r'[^a-z0-9_]'), '_');
    if (lower.isEmpty) {
      return 'fr_acdd';
    }
    if (RegExp(r'^[0-9]').hasMatch(lower)) {
      return 'pkg_$lower';
    }
    return lower;
  }

  String _validatedIdentifier(String value, {required String label}) {
    if (!RegExp(r'^[A-Za-z_]\w*$').hasMatch(value)) {
      throw StateError('$label `$value` is not a valid protobuf identifier.');
    }
    return value;
  }

  String? _apiRefsLine(ExtractedApiSchema api) {
    final refs = <String>[
      ...api.requestRefs.map((ref) => '[$ref]'),
      ...api.responseRefs.map((ref) => '[$ref]'),
    ];
    if (refs.isEmpty) {
      return null;
    }
    return refs.join(', ');
  }
}
